name: Python CI

# Ausführung bei jedem Push oder Pull-Request in den Branch "main"
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Repository auschecken
      - name: Check out the repository
        uses: actions/checkout@v3

      # Python-Umgebung einrichten
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Abhängigkeiten installieren
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Tests ausführen
      - name: Run tests
        run: |
          python -m unittest discover -s tests
